#!/bin/bash

# Example: make-rpm-pkg 0.2.4 4

DC_VER=$1
QT_MAJV=$2
QTTR_DIR=/usr/share/qt${QT_MAJV}/translations

if [ -z "$DC_VER" ]
then
  echo "Version number is missing"
  exit 1
fi

PKG_NAME=doublecontact_${DC_VER}_amd64

# cd .
../make-bin-image ../.. ../.. ../../${PKG_NAME} ${QTTR_DIR}
if [ $? -ne 0 ]; then
  echo "make-bin-image failed!"
  exit 1
fi
# TODO change version number and arch in control file
rpmbuild -bb --buildroot `pwd`/../../${PKG_NAME} ./doublecontact.spec
