#!/bin/bash

# Example: make-dmg-pkg 0.2.4
DC_VER=$1

BUILD_PATH=../../../build-all-desktop_Qt_5_5_1_clang_64bit-Release
QT_PATH=/Users/mac/Qt5.5.1/5.5/clang_64

BUNDLE_MAC_PATH=${BUILD_PATH}/app/doublecontact.app/Contents/MacOS
TRANS_PATH=${BUNDLE_MAC_PATH}/../Translations
mkdir -p ${TRANS_PATH}
# TODO docs

cp ../../translations/*.qm ${TRANS_PATH}/
cp ../../translations/iso639-1.utf8 ${TRANS_PATH}/
cp ${BUILD_PATH}/contconv/contconv ${BUNDLE_MAC_PATH}/
cp ./Info.plist ${BUILD_PATH}/app/doublecontact.app/Contents/
# /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString ${DC_VER}" ${BUILD_PATH}/app/doublecontact.app/Contents/Info.plist
${QT_PATH}/bin/macdeployqt ${BUILD_PATH}/app/doublecontact.app -dmg
mv ${BUILD_PATH}/app/doublecontact.dmg ${BUILD_PATH}/app/doublecontact-${DC_VER}.dmg