#!/bin/bash

SRC_DIR=$1
BLD_DIR=$2
PKG_DIR=$3
QT_MAJV=$4

if ! [ -d ${SRC_DIR} ]; then
  echo "Source directory not exists"
  exit 1
fi
if ! [ -d ${BLD_DIR} ]; then
  echo "Build directory not exists"
  exit 1
fi


BIN_PATH=${PKG_DIR}/usr/bin
TRANS_PATH=${PKG_DIR}/usr/share/doublecontact/translations
DSK_PATH=${PKG_DIR}/usr/share/applications
IMG_PATH=${PKG_DIR}/usr/share/pixmaps
DOC_PATH=${PKG_DIR}/usr/share/doc/doublecontact

mkdir -p ${BIN_PATH}
mkdir -p ${TRANS_PATH}
mkdir -p ${DSK_PATH}
mkdir -p ${IMG_PATH}
mkdir -p ${DOC_PATH}

cp ${BLD_DIR}/app/doublecontact ${BIN_PATH}/
cp ${BLD_DIR}/contconv/contconv ${BIN_PATH}/
cp ${SRC_DIR}/translations/*.qm ${TRANS_PATH}/
cp ${SRC_DIR}/translations/iso639-1.utf8 ${TRANS_PATH}/
cp /usr/share/qt${QT_MAJV}/translations/qt_??.qm ${TRANS_PATH}/
cp /usr/share/qt${QT_MAJV}/translations/qt_??_??.qm ${TRANS_PATH}/
cp ${SRC_DIR}/app/doublecontact.desktop ${DSK_PATH}/
cp ${SRC_DIR}/img/32x32/doublecontact_32x32.xpm ${IMG_PATH}/
cp -r ${SRC_DIR}/doc/* ${DOC_PATH}/
cp ${SRC_DIR}/COPYING ${DOC_PATH}/
cp ${SRC_DIR}/README.md ${DOC_PATH}/
