#!/bin/bash

# Example: make-txz-pkg 0.2.4 4

DC_VER=$1
QT_MAJV=$2

if [ -z "$DC_VER" ]
then
  echo "Version number is missing"
  exit 1
fi

PKG_NAME=doublecontact_${DC_VER}_amd64

# cd .
../make-bin-image ../.. ../../../build-stat ../../../${PKG_NAME} ${QT_MAJV}
if [ $? -ne 0 ]; then
  echo "make-bin-image failed!"
  exit 1
fi
cp ./remove-doublecontact-root-build ../../../${PKG_NAME}/
tar -cJf ../../../${PKG_NAME}.tar.xz `pwd`/../../../${PKG_NAME}

