#!/bin/bash

# Example: make-txz-pkg 0.2.4 /opt/Qt/5.12.12.st

DC_VER=$1
QT_DIR=$2
QTTR_DIR=${QT_DIR}/translations

if [ -z "$DC_VER" ]
then
  echo "Version number is missing"
  exit 1
fi

PKG_NAME=doublecontact_${DC_VER}_amd64

# cd .
../make-bin-image ../.. ../../../build-doublecontact ../../../${PKG_NAME} ${QTTR_DIR}
if [ $? -ne 0 ]; then
  echo "make-bin-image failed!"
  exit 1
fi
cp ./remove-doublecontact-root-build ../../../${PKG_NAME}/
tar -cJf ../../../${PKG_NAME}.tar.xz `pwd`/../../../${PKG_NAME}

