#!/bin/bash

set -o nounset
set -o errexit
# Example: make-deb-pkg 0.1.5 jessie amd64 4
# Example: make-deb-pkg 0.2.0 stretch amd64 4
# Example: make-deb-pkg 0.2.4 buster amd64 4
DC_VER=$1
PKG_DIST=$2
PKG_ARCH=$3
QT_MAJV=$4

if [ -z "$DC_VER" ]
then
  echo "Version number is missing"
  exit 1
fi
if [ -z "$PKG_ARCH" ]
then
  echo "Package architecture is missing"
  exit 1
fi

PKG_NAME=doublecontact_${DC_VER}-${PKG_DIST}_${PKG_ARCH}
CTL_FIlE=./${PKG_NAME}/DEBIAN/control

# Make bin image
cd ../..
./pack/make-bin-image . ./${PKG_NAME} ${QT_MAJV}
# Copy debianization template
cp -R ./pack/deb/DEBIAN ./${PKG_NAME}/
# Add version number and arch to control file
echo "Version: ${DC_VER}" >> ${CTL_FIlE}
echo "Architecture: ${PKG_ARCH}" >> ${CTL_FIlE}
# Add installed size to control file
INST_SIZE=$(du -hks ./${PKG_NAME})
INST_SIZE=(${INST_SIZE//" "/ })
INST_SIZE=${INST_SIZE[0]}
echo "Installed-Size: ${INST_SIZE}" >> ${CTL_FIlE}
# Build!
fakeroot dpkg-deb --build ./${PKG_NAME}/ ./${PKG_NAME}.deb
